### ISSUE TITLE
HTTP 500 error with media_player.turn_off/on

### ISSUE THREAD

**Issue by msbc42** [florianholzapfel/panasonic-viera#13]
HA 0.97.2 on RPi.

Panasonic TH-65FZ950U TV. Toggling On/Off on HA Overview page results in error:

Log Details (ERROR)
Fri Aug 16 2019 12:11:57 GMT+1000 (Australian Eastern Standard Time)
HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 128, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 334, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/panasonic_viera/media_player.py", line 176, in turn_off
    self._remote.turn_off()
  File "/usr/local/lib/python3.7/site-packages/panasonic_viera/__init__.py", line 239, in turn_off
    self.send_key(Keys.power)
  File "/usr/local/lib/python3.7/site-packages/panasonic_viera/__init__.py", line 235, in send_key
    'X_SendKey', params)
  File "/usr/local/lib/python3.7/site-packages/panasonic_viera/__init__.py", line 133, in soap_request
    res = urlopen(req, timeout=5).read()
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by zanac** [comment]
for tunrning on/off tv in your model you should use auth pin.... but it don't work with python3, i opened an issue for this problem.

**Comment by zanac** [comment]
i suggest to close this issue, now it work

**Comment by msbc42** [comment]
Where do I put the auth pin in Home Assistant configuration?

**Comment by florianholzapfel** [comment]
you first need to get an app id and encryption key using your pin. please have a look at the samples in [README.md](https://github.com/florianholzapfel/panasonic-viera/blob/master/README.md).

**Comment by msbc42** [comment]
Yes, I have the app id and key. How do I use them with the Home Assistant integration?????

**Comment by florianholzapfel** [comment]
you would need to ask the home assistant team to add some configuration options for the app id and encryption key.

**Comment by msbc42** [comment]
Wouldn't you also need to use those in your code at the appropriate points? Why is it unto the ha team to modify your package? If they do then that branch would not be updated in future.

**Comment by florianholzapfel** [comment]
you can already use the appid and secret with this package: they can be passed in the constructor. but as far as i have seen, the ha component does not has any configuration options for those values.

those values need to be passed in the following lines:
* https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/panasonic_viera/media_player.py#L88
* https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/panasonic_viera/media_player.py#L93

**Comment by msbc42** [comment]
Hi,

I tried to override the in-built integration with a modified media_play.py, adding the two additional values on the constructor like this:
`
remote = RemoteControl(host, port, app_id="Ac8JSNCBetBLAH==", encryption_key="s4WUYooE39YvCaVFavBLah==")
`

When HA (0.107.6) starts up I see following error:
`
Log Details (ERROR)
Logger: homeassistant.components.media_player
Source: custom_components/panasonic_viera/media_player.py:88
Integration: Media player (documentation, issues)
First occurred: 1:34:30 PM (1 occurrences)
Last logged: 1:34:30 PM

Error while setting up panasonic_viera platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_viera/media_player.py", line 88, in setup_platform
    remote = RemoteControl(host, port, app_id="Ac8JSNCBetBLAH==", encryption_key="s4WUYooE39YvCaVFavBLah==")
TypeError: __init__() got an unexpected keyword argument 'app_id'
`
Am I doing something wrong or is this another issue?

**Comment by ramondunker** [comment]
I believe you must use panasonic_viera.RemoteControl instead of just RemoteControl.


On 27 Mar 2020, at 03:43, msbc42 <notifications@github.com> wrote:

﻿

Hi,

I tried to override the in-built integration with a modified media_play.py, adding the two additional values on the constructor like this:
remote = RemoteControl(host, port, app_id="Ac8JSNCBetBLAH==", encryption_key="s4WUYooE39YvCaVFavBLah==")

When HA (0.107.6) starts up I see following error:
`
Log Details (ERROR)
Logger: homeassistant.components.media_player
Source: custom_components/panasonic_viera/media_player.py:88
Integration: Media player (documentation, issues)
First occurred: 1:34:30 PM (1 occurrences)
Last logged: 1:34:30 PM

Error while setting up panasonic_viera platform for media_player
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
return fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/panasonic_viera/media_player.py", line 88, in setup_platform
remote = RemoteControl(host, port, app_id="Ac8JSNCBetBLAH==", encryption_key="s4WUYooE39YvCaVFavBLah==")
TypeError: init() got an unexpected keyword argument 'app_id'
`
Am I doing something wrong or is this another issue?

**Comment by msbc42** [comment]
I was able to get the integration to start-up correctly with the modified RemoteControl class and my app_id and key.

I'm seeing that the first interaction with the TV  works ok and then the second and subsequent interactions give the HTTP 500 error.

So, if the TV is off I can turn it on from HA but then turning it off in HA fails. If the TV is already on, when I re-start HA, then I can turn it off from HA but then trying to turn it on fails. All further interactions from HA fail until I re-start HA.

**Comment by ramondunker** [comment]
Read the documentation provided bij florianholzapfel. Swap self._remote. for rc.



Ramon

On 28 Mar 2020, at 04:22, msbc42 <notifications@github.com> wrote:

﻿

I was able to get the integration to start-up correctly with the modified RemoteControl class and my app_id and key.

I'm seeing that the first interaction with the TV works ok and then the second and subsequent interactions give the HTTP 500 error.

So, if the TV is off I can turn it on from HA but then turning it off in HA fails. If the TV is already on, when I re-start HA, then I can turn it off from HA but then trying to turn it on fails. All further interactions from HA fail until I re-start HA.

**Comment by msbc42** [comment]
> Read the documentation provided bij florianholzapfel. Swap self._remote. for rc.

Are you referring to the README.md? That covers the command line usage - which works fine.

It stops working when used in HomeAssistant - which is what this case was all about.
