### ISSUE TITLE
TX-32DSX609 not answering

### ISSUE THREAD

**Issue by akloeckner** [florianholzapfel/panasonic-viera#19]
I'm trying to connect to my TX-32DSX609, but it does not seem to answer. I tried to manually follow the code, but only got so far as to GET the first URL: `http://IP:55000/nrc/sdd_0.xml`. 

It returns the following:
```
<?xml version="1.0"?>
<scpd xmlns="urn:schemas-upnp-org:service-1-0">
  <specVersion><major>1</major><minor>0</minor></specVersion>
  <actionList>
    <action>
      <name>X_SendKey</name>
      <argumentList>
        <argument>
          <name>X_KeyEvent</name>
          <direction>in</direction>
          <relatedStateVariable>X_KeyEvent</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_SendString</name>
      <argumentList>
        <argument>
          <name>X_String</name>
          <direction>in</direction>
          <relatedStateVariable>X_String</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_GetInputMode</name>
      <argumentList>
        <argument>
          <name>X_InputMode</name>
          <direction>out</direction>
          <relatedStateVariable>X_InputMode</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_GetKeyboardType</name>
      <argumentList>
        <argument>
          <name>X_KeyboardType</name>
          <direction>out</direction>
          <relatedStateVariable>X_KeyboardType</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_GetVectorInfo</name>
      <argumentList>
        <argument>
          <name>X_PortNumber</name>
          <direction>out</direction>
          <relatedStateVariable>X_PortNumber</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_GetGamepadInfo</name>
      <argumentList>
        <argument>
          <name>X_PortNumber</name>
          <direction>out</direction>
          <relatedStateVariable>X_PortNumber</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_GetAppInfo</name>
      <argumentList>
        <argument>
          <name>X_InfoType</name>
          <direction>in</direction>
          <relatedStateVariable>X_InfoType</relatedStateVariable>
        </argument>
        <argument>
          <name>X_AppInfo</name>
          <direction>out</direction>
          <relatedStateVariable>X_AppInfo</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_LaunchApp</name>
      <argumentList>
        <argument>
          <name>X_AppType</name>
          <direction>in</direction>
          <relatedStateVariable>X_AppType</relatedStateVariable>
        </argument>
        <argument>
          <name>X_LaunchKeyword</name>
          <direction>in</direction>
          <relatedStateVariable>X_LaunchKeyword</relatedStateVariable>
        </argument>
        <argument>
          <name>X_SessionId</name>
          <direction>out</direction>
          <relatedStateVariable>X_SessionId</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_ConnectApp</name>
      <argumentList>
        <argument>
          <name>X_AppType</name>
          <direction>in</direction>
          <relatedStateVariable>X_AppType</relatedStateVariable>
        </argument>
        <argument>
          <name>X_SessionId</name>
          <direction>in</direction>
          <relatedStateVariable>X_SessionId</relatedStateVariable>
        </argument>
        <argument>
          <name>X_ConnectKeyword</name>
          <direction>in</direction>
          <relatedStateVariable>X_ConnectKeyword</relatedStateVariable>
        </argument>
        <argument>
          <name>X_ConnectAddr</name>
          <direction>in</direction>
          <relatedStateVariable>X_ConnectAddr</relatedStateVariable>
        </argument>
        <argument>
          <name>X_Message</name>
          <direction>out</direction>
          <relatedStateVariable>X_Message</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_QueryApp</name>
      <argumentList>
        <argument>
          <name>X_AppType</name>
          <direction>in</direction>
          <relatedStateVariable>X_AppType</relatedStateVariable>
        </argument>
        <argument>
          <name>X_SessionId</name>
          <direction>in</direction>
          <relatedStateVariable>X_SessionId</relatedStateVariable>
        </argument>
        <argument>
          <name>X_QueryKeyword</name>
          <direction>in</direction>
          <relatedStateVariable>X_QueryKeyword</relatedStateVariable>
        </argument>
        <argument>
          <name>X_Message</name>
          <direction>out</direction>
          <relatedStateVariable>X_Message</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_GetEventServerUrl</name>
      <argumentList>
        <argument>
          <name>X_EventServerUrl</name>
          <direction>out</direction>
          <relatedStateVariable>X_EventServerUrl</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
  </actionList>
  <serviceStateTable>
    <stateVariable sendEvents="no">
      <name>X_KeyEvent</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_String</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>X_InputMode</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>X_KeyboardType</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_PortNumber</name>
      <dataType>ui2</dataType>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>X_ScreenState</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_InfoType</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>X_AppInfo</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_AppType</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_LaunchKeyword</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_SessionId</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_ConnectKeyword</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_ConnectAddr</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_Message</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_QueryKeyword</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>X_EventServerUrl</name>
      <dataType>string</dataType>
    </stateVariable>
  </serviceStateTable>
</scpd>
```

So, i assume, some API is available. But all commands I send (through the console e.g.) immediately return and say my is switched off (which is not true):

```
(homeassistant-release) homeassistant@ak-test:/srv/homeassistant$ python3 -m panasonic_viera IP --verbose
> get_volume
DEBUG:panasonic_viera:Sending to http://IP:55000/dmr/control_0:
{'Host': 'IP:55000', 'Content-Length': 328, 'SOAPAction': '"urn:schemas-upnp-org:service:RenderingControl:1#GetVolume"', 'Content-Type': 'text/xml; charset=utf-8"'}
b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><m:GetVolume xmlns:m="urn:schemas-upnp-org:service:RenderingControl:1"><InstanceID>0</InstanceID><Channel>Master</Channel></m:GetVolume></s:Body></s:Envelope>'
TV is switched off.
>
(homeassistant-release) homeassistant@ak-test:/srv/homeassistant$ exit
```

Am I missing anything? Or is my tv just not supported (yet)? Where should I look next? 

Thanks for your help!

**Comment by florianholzapfel** [comment]
the repl hides all exception information. can you please run the following snippet and post the output here. thanks.

```python

import argparse
import logging
import panasonic_viera

parser = argparse.ArgumentParser(prog='panasonic_viera',
                description='Remote control a Panasonic Viera TV.')
parser.add_argument('host', metavar='host', type=str,
                help='Address of the Panasonic Viera TV')
parser.add_argument('port', metavar='port', type=int, nargs='?',
                default=panasonic_viera.DEFAULT_PORT,
                help='Port of the Panasonic Viera TV. Defaults to {}.'.format(panasonic_viera.DEFAULT_PORT))
parser.add_argument('--verbose', dest='verbose', action='store_const',
                const=True, default=False,
                help='debug output')
args = parser.parse_args()

if args.verbose:
    logging.basicConfig(level=logging.DEBUG)

rc = panasonic_viera.RemoteControl(args.host, args.port)
rc.get_volume()
```

**Comment by akloeckner** [comment]
Thank for your answer! Yes, now there's more output. TL;DR: 403 forbidden... Did I miss some authentication instruction?

```
(homeassistant-release) homeassistant@ak-test:/srv/homeassistant$ python3 panasonic.py --verbose IP
DEBUG:panasonic_viera:Sending to http://IP:55000/dmr/control_0:
{'SOAPAction': '"urn:schemas-upnp-org:service:RenderingControl:1#GetVolume"', 'Host': 'IP:55000', 'Content-Type': 'text/xml; charset=utf-8"', 'Content-Length': 328}
b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><m:GetVolume xmlns:m="urn:schemas-upnp-org:service:RenderingControl:1"><InstanceID>0</InstanceID><Channel>Master</Channel></m:GetVolume></s:Body></s:Envelope>'
Traceback (most recent call last):
  File "panasonic.py", line 21, in <module>
    rc.get_volume()
  File "/srv/homeassistant-release/lib/python3.5/site-packages/panasonic_viera/__init__.py", line 197, in get_volume
    'GetVolume', params)
  File "/srv/homeassistant-release/lib/python3.5/site-packages/panasonic_viera/__init__.py", line 133, in soap_request
    res = urlopen(req, timeout=5).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by florianholzapfel** [comment]
you probably need to enable the remote control app in your tv settings. please have a look at the configuration tab on https://av.jpn.support.panasonic.com/support/global/cs/tv/vremote2/android/ for this.

**Comment by akloeckner** [comment]
Thanks for your help! I had that turned on already. But your hint pointed me to the original app and its help. It turns out that both the app and the TV need to be on the same subnet. (They always say that, but it's never been true for any of my devices so far.) It seems, here, this is some kind of security measure. Changing the subnet of the TV didn't suffice (due to routing problems then, I guess). I now put the TV on my main WiFi, and it works now!

Thanks for your effort in this! And for your help!
