### ISSUE TITLE
Latest version not working with python 3

### ISSUE THREAD

**Issue by gorpet** [florianholzapfel/panasonic-viera#20]
Unfortunately latest version 0.3.2.3 does not work with python 3 (used in home assistant) due to commit: #https://github.com/florianholzapfel/panasonic-viera/commit/38da8440e31ef2efe3d6739bff67e9bfa051e933
```
>>> import panasonic_viera
>>> rc = panasonic_viera.RemoteControl("HOST", app_id="xxxxxxxx==", encryption_key="xxxxxxxx==")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/panasonic-viera/panasonic_viera/__init__.py", line 163, in __init__
    self._derive_session_keys()
  File "/root/panasonic-viera/panasonic_viera/__init__.py", line 261, in _derive_session_keys
    iv_vals = [ord(c) for c in iv]
  File "/root/panasonic-viera/panasonic_viera/__init__.py", line 261, in <listcomp>
    iv_vals = [ord(c) for c in iv]
TypeError: ord() expected string of length 1, but int found
```

**Comment by florianholzapfel** [comment]
fixed with 0.3.3
