### ISSUE TITLE
Python 3 incompatible

### ISSUE THREAD

**Issue by zanac** [florianholzapfel/panasonic-viera#22]
Python 2.7 is end of life, please make it compatible with python 3

**Comment by florianholzapfel** [comment]
version 0.3.3 should already be compatible with python 3. have you experienced any specific problems?

**Comment by zanac** [comment]
The problem is using app_id and encryption_key

Traceback (most recent call last):                                                                                                                            
  File "./mysample.py", line 2, in <module>                                                                                                                   
    rc = panasonic_viera.RemoteControl("192.168.2.100", app_id="xxxxx", encryption_key="xxxxx")                                 
  File "/home/vanni/src/pana3/panasonic-viera-0.3.3/panasonic_viera/__init__.py", line 163, in __init__                                                       
    self._derive_session_keys()                                                                                                                               
  File "/home/vanni/src/pana3/panasonic-viera-0.3.3/panasonic_viera/__init__.py", line 261, in _derive_session_keys                                           
    iv_vals = [ord(c) for c in iv]                                                                                                                            
  File "/home/vanni/src/pana3/panasonic-viera-0.3.3/panasonic_viera/__init__.py", line 261, in <listcomp>                                                     
    iv_vals = [ord(c) for c in iv]           
TypeError: ord() expected string of length 1, but int found

**Comment by zanac** [comment]
please note also if i remove ord( function i have an error below, allt he code that use AES encryption is broken

Traceback (most recent call last):                                                                                                                            
  File "./mysample.py", line 2, in <module>                                                                                                                   
    rc = panasonic_viera.RemoteControl("192.168.2.100", app_id="AepElgAOxM4gGA==", encryption_key="FWTPYgZIT+ydC0sBGv6lxg==")                                 
  File "/home/vanni/src/pana3/panasonic-viera-0.3.3/panasonic_viera/__init__.py", line 164, in __init__                                                       
    self._request_session_id()                                                                                                                                
  File "/home/vanni/src/pana3/panasonic-viera-0.3.3/panasonic_viera/__init__.py", line 383, in _request_session_id                                            
    self._session_hmac_key)                                                                                                                                   
  File "/home/vanni/src/pana3/panasonic-viera-0.3.3/panasonic_viera/__init__.py", line 286, in _encrypt_soap_payload                                          
    payload += struct.pack(">I", len(data))                                                                                                                   
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by ngws** [comment]
New PR https://github.com/florianholzapfel/panasonic-viera/pull/23 created that should fix this, please test.

**Comment by ngws** [comment]
PR #23 was closed due to issues with encoding. I have now created PR #25 which I have tested on both Python 3.8 and Python 2.7 without any issues. Please test and make any comments there.

**Comment by zanac** [comment]
latest patch work well
